version: '3.7'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freetour
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 10000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    image: tuichain-backend
    container_name: tuichain-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 10001:8000
    env_file:
      - ./.env.backend
